version: '3.3'
services:
  app:
    build:
      context: ../..
      dockerfile: traincompany/ops-tools/docker/images/app/Dockerfile
    command: sh -c "mvn package; java -jar ./traincompany/target/traincompany-1.0-SNAPSHOT.jar"
    volumes:
      - ../../:/app
    networks:
      - traincompany-net
    ports:
      - 8090:8090
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1-alpine
    restart: always
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ../../data/dump:/db-dump
    networks:
      - traincompany-net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=traincompany

networks:
  traincompany-net:
