version: '3.3'
services:
  app:
    build:
      context: ../..
      dockerfile: metasearchservice/ops-tools/docker/images/app/Dockerfile
    command: sh -c "mvn package; java -jar ./metasearchservice/target/metasearchservice-1.0-SNAPSHOT.jar"
    volumes:
      - ../../:/app
    networks:
      - search-net
    ports:
      - 9080:9080
  zookeeper:
    image: bitnami/zookeeper:3.8.0-debian-11-r36
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:3.3.1
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
networks:
  search-net: