version: '3.3'
services:
  app:
    build:
      context: ../..
      dockerfile: shipcompany/ops-tools/docker/images/app/Dockerfile
    command: sh -c "mvn package; java -jar ./shipcompany/target/shipcompany-1.0-SNAPSHOT.jar"
    volumes:
      - ../../:/app
    networks:
      - shipcompany-net
    ports:
      - 9050:9050
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1-alpine
    restart: always
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ../../data/dump:/db-dump
    networks:
      - shipcompany-net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shipcompany

networks:
  shipcompany-net:
